/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBAppSwitcherScrollViewDelegate-Protocol.h"

@class NSMutableArray, SBAppSwitcherScrollView, SBLinenView, UIImageView, UIView;

@interface SBAppSwitcherBarView : _ABAddressBookCopyLocalizedLabel <SBAppSwitcherScrollViewDelegate>
{
    id <SBAppSwitcherBarViewDelegate> _delegate;
    NSMutableArray *_appIcons;
    UIView *_contentView;
    SBLinenView *_backgroundView;
    NSMutableArray *_auxViews;
    SBAppSwitcherScrollView *_scrollView;
    UIImageView *_topShadowView;
    UIImageView *_bottomShadowView;
    BOOL _animateContentReflow;
    BOOL _animatedScrolling;
    int _lastPageIndex;
    BOOL _isVisible;
}

+ (unsigned int)iconsPerPage:(int)fp8;
+ (struct CGSize)viewSize:(int)fp8;
+ (float)edgePaddingForWidth:(float)fp8;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (void)prepareForDisplay:(id)fp8;
- (id)appIcons;
- (void)positionForHidden;
- (void)positionForRevealed;
- (void)setEditing:(BOOL)fp8;
- (BOOL)isScrolling;
- (void)addIcon:(id)fp8;
- (void)removeIcon:(id)fp8;
- (void)replaceIcons:(id)fp8 with:(id)fp12;
- (void)addAuxiliaryViews:(id)fp8;
- (id)applicationIconForDisplayIdentifier:(id)fp8;
- (BOOL)nowPlayingControlsVisible;
- (BOOL)airPlayControlsVisible;
- (void)viewWillAppear;
- (void)viewWillDisappear;
- (void)_iconRemoveDidStop:(id)fp8 finished:(id)fp12 context:(id)fp16;
- (void)_reflowContent:(BOOL)fp8;
- (void)_adjustContentOffsetForReflow:(BOOL)fp8;
- (void)_adjustContentOffsetForResizeFromOldOffset:(struct CGPoint)fp8 andOldSize:(struct CGSize)fp16 toNewSize:(struct CGSize)fp24;
- (void)_adjustScrollContentSize;
- (void)_positionAtFirstPage:(BOOL)fp8;
- (void)layoutSubviews;
- (struct CGRect)_iconFrameForIndex:(unsigned int)fp8 withSize:(struct CGSize)fp12;
- (unsigned int)_pageCount;
- (unsigned int)_iconCountForWidth:(float)fp8;
- (struct CGPoint)_firstPageOffset:(struct CGSize)fp8;
- (int)_pageForOffset:(struct CGPoint)fp8 withSize:(struct CGSize)fp16;
- (int)_pageForIndex:(unsigned int)fp8;
- (void)didMoveToSuperview;
- (void)scrollViewDidScroll:(id)fp8;
- (void)scrollViewDidEndScrollingAnimation:(id)fp8;
- (void)scrollViewDidEndDragging:(id)fp8 willDecelerate:(BOOL)fp12;
- (void)scrollViewDidEndDecelerating:(id)fp8;
- (BOOL)scrollView:(id)fp8 shouldCancelInContentForView:(id)fp12;
- (id)delegate;
- (void)setDelegate:(id)fp8;

@end

